version: '3.8'

services:
  f1-telemetry:
    build:
      context: ../cmd/f1-telemetry-app
    container_name: f1-telemetry
    ports:
      - 8080:8080
      - 20777:20777/udp
    expose:
      - 8080
      - 20777/udp

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s

volumes:
  prometheus-data:
  grafana-data:

