version: '3.8'

services:
  f1-telemetry:
    build:
      context: ../cmd/f1-telemetry-app
    container_name: f1-telemetry
    ports:
      - 8080:8080
      - 20777:20777/udp
    expose:
      - 8080
      - 20777/udp

  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    expose:
      - 9090

  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:

