{
 "title": "F1 Telemetry Client Go",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes, pod)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Speed Trap",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_speed_trap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Front Left Tyre Wear ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",tyre=\"fl\"}"
    }
   ]
  },
  {
   "title": "Front Right Tyre Wear ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",tyre=\"fr\"}"
    }
   ]
  },
  {
   "title": "Tyre Age Lap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "f1_telemetry_tyres_age_lap{}" }
   ]
  },
  {
   "title": "Front Left Tyre Brake Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_brake_temp{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",brake=\"fl\"}"
    }
   ]
  },
  {
   "title": "Front Right Tyre Brake Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_brake_temp{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",brake=\"fr\"}"
    }
   ]
  },
  {
   "title": "Fastest Lap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_fastest_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Current Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_car_speed{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Rear Left Tyre Wear ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",tyre=\"rl\"}"
    }
   ]
  },
  {
   "title": "Rear Right Tyre Wear ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",tyre=\"rr\"}"
    }
   ]
  },
  {
   "title": "Engine Damage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",tyre=\"rr\"}"
    }
   ]
  },
  {
   "title": "Rear Left Tyre Brake Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_brake_temp{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",brake=\"rl\"}"
    }
   ]
  },
  {
   "title": "Rear Right Tyre Brake Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_brake_temp{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",brake=\"rr\"}"
    }
   ]
  },
  {
   "title": "Last Lap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_last_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Car Speed Monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    { "expr": "f1_telemetry_car_speed{}", "legendFormat": "car speed" }
   ]
  },
  {
   "title": "Car Engime RPM",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "f1_telemetry_car_engine_rpm{}", "legendFormat": "car engine rpm" }
   ]
  }
 ]
}